"""Generate a SUMIT KEY moat report from code, tests, and evidence."""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


MOAT_AREAS: list[dict[str, Any]] = [
    {
        "id": "human_session_kdf",
        "name": "Human-session KDF",
        "thesis": "Live behavior is additive cryptographic input, never the only secret.",
        "paths": [
            "behave_kdf.py",
            "entropy_engine.py",
            "key_generator.py",
            "tests/test_entropy_sources_deep.py",
            "tests/test_research_evidence.py",
        ],
        "evidence_key": "behavioral_kdf",
    },
    {
        "id": "ghost_handoff",
        "name": "Volunteer ghost handoff",
        "thesis": "A portable package opens once, burns its key, and states its boundary honestly.",
        "paths": [
            "api.py",
            "browser_extension/popup.js",
            "scripts/sandbox_demo.py",
            "tests/test_ghost_api.py",
            "tests/test_sandbox_demo_script.py",
        ],
        "evidence_key": "ghost_once",
    },
    {
        "id": "platform_bound_encryption",
        "name": "Platform-bound personal encryption",
        "thesis": "Apps become untrusted pipes; platform/context replay fails.",
        "paths": [
            "sdk/identity.py",
            "sdk/core.py",
            "sdk/sumitkey.js",
            "tests/test_identity.py",
            "tests/test_connectivity.py",
        ],
        "evidence_key": "platform_replay",
    },
    {
        "id": "claim_hygiene",
        "name": "Claim hygiene",
        "thesis": "Every public claim maps to code, tests, limits, and validation status.",
        "paths": [
            "claim_matrix.json",
            "SECURITY_LIMITATIONS.md",
            "RESEARCH_CONTRIBUTIONS.md",
            "NOVELTY_POSITIONING.md",
            "tests/test_security_audit.py",
        ],
        "evidence_key": None,
    },
    {
        "id": "reproducible_evidence",
        "name": "Reproducible evidence pipeline",
        "thesis": "The moat can be regenerated by scripts and checked in CI.",
        "paths": [
            "scripts/ci_check.py",
            "scripts/research_evidence.py",
            "scripts/moat_report.py",
            ".github/workflows/ci.yml",
            "results/research_evidence.json",
        ],
        "evidence_key": None,
    },
]


def _load_json(path: Path) -> dict[str, Any] | None:
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def build_moat_report(
    *,
    evidence_path: Path = ROOT / "results/research_evidence.json",
) -> dict[str, Any]:
    evidence = _load_json(evidence_path)
    experiments = (evidence or {}).get("experiments", {})
    claim_matrix = (evidence or {}).get("claim_matrix", {})

    areas: list[dict[str, Any]] = []
    for area in MOAT_AREAS:
        missing_paths = [path for path in area["paths"] if not (ROOT / path).exists()]
        evidence_key = area["evidence_key"]
        if evidence_key is None:
            evidence_status = "not_required"
            evidence_passed = True
        elif evidence_key in experiments:
            evidence_passed = bool(experiments[evidence_key].get("passed"))
            evidence_status = "passed" if evidence_passed else "failed"
        else:
            evidence_passed = False
            evidence_status = "missing"

        area_passed = not missing_paths and evidence_passed
        areas.append(
            {
                "id": area["id"],
                "name": area["name"],
                "thesis": area["thesis"],
                "paths_checked": area["paths"],
                "missing_paths": missing_paths,
                "evidence_key": evidence_key,
                "evidence_status": evidence_status,
                "passed": area_passed,
            }
        )

    report = {
        "schema": "sumit-key-moat-report-v1",
        "generated_at_unix": time.time(),
        "moat_thesis": (
            "Human-session-owned cryptography: live behavior, OS randomness, "
            "user-held identity, platform context, one-time handoff, and claim "
            "hygiene as one tested lifecycle."
        ),
        "evidence_path": str(evidence_path.relative_to(ROOT)) if evidence_path.is_relative_to(ROOT) else str(evidence_path),
        "evidence_loaded": evidence is not None,
        "claim_matrix_passed": bool(claim_matrix.get("passed", False)),
        "areas": areas,
    }
    report["passed"] = report["evidence_loaded"] and report["claim_matrix_passed"] and all(
        area["passed"] for area in areas
    )
    return report


def render_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# SUMIT KEY Moat Report",
        "",
        f"Passed: `{report['passed']}`",
        "",
        "## Thesis",
        "",
        report["moat_thesis"],
        "",
        "## Areas",
        "",
        "| Area | Evidence | Missing Paths | Status |",
        "|---|---|---|---|",
    ]
    for area in report["areas"]:
        missing = ", ".join(area["missing_paths"]) if area["missing_paths"] else "none"
        lines.append(
            f"| {area['name']} | {area['evidence_status']} | {missing} | {area['passed']} |"
        )
    lines.extend(
        [
            "",
            "## Boundary",
            "",
            "This report proves project defensibility artifacts exist and pass local engineering checks. "
            "It does not claim official certification or that every underlying idea is new.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate SUMIT KEY moat report.")
    parser.add_argument("--evidence", default="results/research_evidence.json")
    parser.add_argument("--output-md", default="results/moat_report.md")
    parser.add_argument("--output-json", default="results/moat_report.json")
    args = parser.parse_args()

    report = build_moat_report(evidence_path=ROOT / args.evidence)
    json_path = ROOT / args.output_json
    md_path = ROOT / args.output_md
    json_path.parent.mkdir(parents=True, exist_ok=True)
    md_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    md_path.write_text(render_markdown(report), encoding="utf-8")
    try:
        json_display = json_path.relative_to(ROOT)
    except ValueError:
        json_display = json_path
    try:
        md_display = md_path.relative_to(ROOT)
    except ValueError:
        md_display = md_path
    print(f"wrote {json_display}")
    print(f"wrote {md_display}")
    print(f"passed={report['passed']}")
    return 0 if report["passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
